# ----------------------- #
#      Main Configs       #
# ----------------------- #
title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "localhost"
default_asides: []
sidebar: collapse

# Build settings
theme: jekyll-lenciel-theme
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-feed
gems: []
exclude:
  - Gemfile
  - Gemfile.lock
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
permalink: /:year/:month/:title/
encoding: utf-8

# plugins
plugins_dir: ./plugins
safe: false
# include_code.rb
code_dir: downloads/code
# category_generator
category_dir: categories

highlighter: rouge
paginate: 2          # Posts per page on the blog index
paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase

# jekyll-picture-tag
picture:
  output: "../resized"
  cdn_url: "https://cdn.lenciel.com"
  cdn_environments: ['production']
  suppress_warnings: true

# Google Analytics
google_analytics_tracking_id: UA-175991-6

# Facebook Like
facebook_like: false

# Beian
beian: 沪ICP备xxxxxxxxx号
