source "https://rubygems.org"

gem "jekyll", ">= 3.6", "< 5.0"
gem "jekyll-lenciel-theme", path: "../"


group :jekyll_plugins do
   gem 'jekyll-paginate'
   gem 'jekyll-gist'
   gem 'jekyll_picture_tag'
   gem 'jekyll-sitemap'
   gem 'jekyll-feed'
   gem 'pygments.rb'
   gem 'stringex'
   # gems below are installed for rake task
   gem 'colorize'
   gem 'html_compressor'
   gem 'parallel'
   gem 'ruby-progressbar'
end