source "https://rubygems.org"

gem "jekyll", "3.4.3"
gem "jekyll-lenciel-theme", path: "../"


group :jekyll_plugins do
   gem 'rdiscount', '~> 2.2.0'
   gem 'stringex', '~> 2.7.1'
   gem 'haml', '~> 4.0.7'
   gem 'rubypants', '~> 0.6.0'
   gem 'octopress-hooks', '~> 2.6.2'
   gem 'octopress-date-format', '~> 3.0.3'
   gem 'jekyll-sitemap'
   gem 'sass-globbing', '~> 1.0.0'
   gem 'colorize'
   gem "pygments.rb"
end