source "https://rubygems.org"

gem "jekyll", "4.0.0"
gem "jekyll-lenciel-theme", path: "../"


group :jekyll_plugins do
   gem 'jekyll-paginate'
   gem 'jekyll-gist'
   gem 'jekyll-responsive-image'
   gem 'jekyll-sitemap'
   gem 'pygments.rb'
   gem 'stringex'
   gem 'jekyll-feed'
end