# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Site settings

# 1. Files excluded from Jekyll builds
exclude:
  - README.md
  - LICENSE
  - CNAME
  - sass
  - assets/javascripts/libs/*.js
  - Gemfile
  - Gemfile.lock
  - jekyll-lenciel-theme.gemspec
  - .jekyll-cache

# 2. Installed Gems (you still have to gem install them or you can change the Gemfile)
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll_picture_tag

# 3. Gem settings

# jekyll-paginate
paginate: 2 # Posts per page on the blog index
paginate_path: "posts/:num" # Directory base for pagination URLs eg. /posts/2/
# include_code.rb
code_dir: downloads/code
# category_generator
category_dir: categories
titlecase: true # Converts page and post titles to titlecase

# jekyll-picture-tag
picture:
  output: "resized"
  fast_build: true
  cdn_url: "http://cdn.lenciel.com"
  cdn_environments: ["production"]
  suppress_warnings: true
  noscript: true # add a fallback image inside a <noscript> tag.

# jekyll-archives

jekyll-archives:
  enabled:
    - year
  layout: yarchive

# google analytics

# facebook kike
facebook_like: false
# Beian
beian: 沪ICP备xxxxxxxxx号

# Gitalk
comment_appId: gzGzoHsz
comment_appKey: PjJJiU2

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: /:year/:month/:title/
highlighter: rouge
recent_posts: 5 # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;" # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"
# sidebar: collapse
theme: jekyll-lenciel-theme
plugins_dir: ./plugins
safe: false

# 5. Site settings
encoding: utf-8 # Make sure the encoding is right
title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://localhost.prod"
static_base: "https://cdn.lenciel.com"
simple_search: true
feed:
  excerpt_only: true
